# Generated by Django 5.2.8 on 2026-05-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_remove_reserva_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='precio',
            field=models.IntegerField(default=12000),
        ),
    ]
