# Generated by Django 5.2.8 on 2026-05-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_asiento_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=3500, max_digits=10),
        ),
    ]
