# Generated by Django 5.2.8 on 2026-06-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0004_sala_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('categoria', models.CharField(choices=[('combo', 'Combo'), ('bebida', 'Bebida'), ('alimento', 'Alimento'), ('merch', 'Merch')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
