# Generated by Django 5.2.8 on 2026-07-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0005_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='anuncios/')),
                ('activo', models.BooleanField(default=True)),
                ('posicion', models.CharField(choices=[('top', 'Arriba'), ('middle', 'Medio'), ('bottom', 'Abajo')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
